export const pokemonTypes = [
  'normal',
  'fighting',
  'flying',
  'poison',
  'ground',
  'rock',
  'bug',
  'ghost',
  'fire',
  'water',
  'grass',
  'electric',
  'psychic',
  'ice',
  'dragon',
  'steel',
  'dark',
  'fairy',
];

export const allGenerations = [
  { number: 1, show: true },
  { number: 2, show: true },
  { number: 3, show: true },
  { number: 4, show: true },
  { number: 5, show: true },
  { number: 6, show: true },
  { number: 7, show: true },
];
